import * as fs from 'fs';
import * as path from 'path';
import { ReactComponent, FrontendRouteConfig } from './react/types';
import { ReactComponentGenerator } from './react/componentGenerator';
import { ReactComponentRegistry } from './react/componentRegistry';
import { ProductIssue } from './issueStream';
import { SeimConfig } from './types';
import { SeimEventBus } from './events';
import { Logger } from './logger';

export interface FrontendChange {
  component: ReactComponent;
  filePath: string;
}

export class FrontendEvolver {
  constructor(
    private generator: ReactComponentGenerator,
    private registry: ReactComponentRegistry,
    private config: SeimConfig,
    private events: SeimEventBus,
    private logger: Logger,
  ) {}

  public async evolve(issue: ProductIssue): Promise<FrontendChange | null> {
    try {
      const sanitized = issue.path.replace(/[^a-zA-Z0-9]/g, ' ').trim();
      const rawName = sanitized
        .split(/\s+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('') || 'Evolved';

      const componentName = `${rawName}Page`;
      const component = await this.generator.generate({
        name: componentName,
        routePath: issue.path,
        intent: issue.suggestedAction,
        applicationContext: this.config.frontend?.applicationContext,
        isPage: true,
      });

      const outputDir = this.config.frontend?.outputDir || path.join(process.cwd(), 'src', 'seim-generated');
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      const filePath = path.join(outputDir, `${componentName}.tsx`);
      await fs.promises.writeFile(filePath, component.code, 'utf8');
      this.logger.info(`[FrontendEvolver] Wrote React component to ${filePath}`);

      // Update the seim-routes.tsx and seim-routes.json manifests
      await this.updateRouteManifest(outputDir);

      // Optional HMR trigger signal file
      if (this.config.frontend?.hmrSignalPath) {
        await this.writeHmrSignal(component);
      }

      (this.events as any).emitEvent?.('frontend:evolved', { component, filePath, issue });
      (this.events as any).emit?.('frontend:evolved', { component, filePath, issue });

      return { component, filePath };
    } catch (err: any) {
      this.logger.error(`[FrontendEvolver] Failed to evolve frontend for ${issue.path}: ${err?.message}`);
      return null;
    }
  }

  private async updateRouteManifest(outputDir: string): Promise<void> {
    try {
      const routes = this.registry.getRoutes();
      const manifestCode = `// [Auto-Generated by SEIM - Do Not Edit Manually]
import React, { lazy } from 'react';

export interface SeimRouteDefinition {
  path: string;
  name: string;
  Component: React.ComponentType<any>;
}

export const seimGeneratedRoutes: SeimRouteDefinition[] = [
${routes.map(r => `  {
    path: '${r.path}',
    name: '${r.componentName}',
    Component: lazy(() => import('./${r.componentName}')),
  },`).join('\n')}
];

export function SeimDynamicRoutes(): JSX.Element {
  return (
    <>
      {seimGeneratedRoutes.map(r => (
        <React.Fragment key={r.path} />
      ))}
    </>
  );
}
`;
      const manifestPath = path.join(outputDir, 'seim-routes.tsx');
      await fs.promises.writeFile(manifestPath, manifestCode, 'utf8');

      const jsonManifestPath = path.join(outputDir, 'seim-routes.json');
      await fs.promises.writeFile(
        jsonManifestPath,
        JSON.stringify({ routes, updatedAt: Date.now() }, null, 2),
        'utf8'
      );
    } catch (err: any) {
      this.logger.warn(`[FrontendEvolver] Could not update route manifest: ${err?.message}`);
    }
  }

  private async writeHmrSignal(component: ReactComponent): Promise<void> {
    try {
      const signalPath = this.config.frontend!.hmrSignalPath!;
      const dir = path.dirname(signalPath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      await fs.promises.writeFile(
        signalPath,
        JSON.stringify({ componentId: component.id, name: component.name, timestamp: Date.now() }),
        'utf8'
      );
    } catch {
      // Best-effort HMR signal
    }
  }
}
