import * as fs from 'fs';
import * as path from 'path';

export interface ChangelogEntry {
  id: string;
  type: 'optimization' | 'bug_fix' | 'new_feature' | 'ux_improvement' | 'rollback';
  title: string;
  description: string;
  path: string;
  code?: string;
  diff?: string;
  affectedSessions?: number;
  latencyImprovement?: string;
  shippedAt: number;
  rolledBackAt?: number;
  status: 'live' | 'rolled_back';
  triggerIssueId?: string;
}

export class ProductChangelog {
  private entries: ChangelogEntry[] = [];
  private readonly MAX_ENTRIES = 500;
  private persistPath?: string;

  constructor(storagePath: string | null = './.seim-storage') {
    this.persistPath = storagePath ? path.join(storagePath, 'changelog.json') : undefined;
    this.load();
  }

  public record(entry: Omit<ChangelogEntry, 'id' | 'shippedAt'>): ChangelogEntry {
    const fullEntry: ChangelogEntry = {
      id: `chg_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`,
      shippedAt: Date.now(),
      ...entry,
    };

    this.entries.unshift(fullEntry);
    if (this.entries.length > this.MAX_ENTRIES) {
      this.entries.pop();
    }
    this.save();
    return fullEntry;
  }

  public rollback(routePath: string, reason: string): boolean {
    const target = this.entries.find(e => (e.path === routePath || e.path === routePath.trim()) && e.status === 'live');
    if (target) {
      target.status = 'rolled_back';
      target.rolledBackAt = Date.now();
      this.record({
        type: 'rollback',
        title: `Rollback: ${routePath}`,
        description: `Automated/Manual rollback triggered: ${reason}`,
        path: routePath,
        status: 'rolled_back',
      });
      this.save();
      return true;
    }
    return false;
  }

  public getRecent(limit: number = 50): ChangelogEntry[] {
    return this.entries.slice(0, limit);
  }

  public getAll(): ChangelogEntry[] {
    return [...this.entries];
  }

  public toMarkdown(): string {
    if (this.entries.length === 0) {
      return '# Product Evolution Changelog\n\nNo autonomous changes recorded yet.';
    }

    let md = '# 🚀 Product Evolution Changelog\n\n';
    md += 'Autonomous improvements, bug fixes, and feature rollouts generated by SEIM:\n\n';

    for (const entry of this.entries) {
      const date = new Date(entry.shippedAt).toISOString().split('T')[0];
      const time = new Date(entry.shippedAt).toLocaleTimeString();
      const statusIcon = entry.status === 'live' ? '✅' : '↩️';
      
      md += `### ${statusIcon} [${entry.type.toUpperCase()}] ${entry.title} (${date} ${time})\n`;
      md += `- **Path**: \`${entry.path}\`\n`;
      md += `- **Impact**: ${entry.description}\n`;
      if (entry.latencyImprovement) {
        md += `- **Performance**: ${entry.latencyImprovement}\n`;
      }
      if (entry.affectedSessions) {
        md += `- **Affected Visitor Sessions**: ${entry.affectedSessions}\n`;
      }
      if (entry.status === 'rolled_back' && entry.rolledBackAt) {
        md += `- **Rolled Back At**: ${new Date(entry.rolledBackAt).toLocaleTimeString()}\n`;
      }
      md += '\n---\n\n';
    }

    return md;
  }

  private save(): void {
    if (!this.persistPath) return;
    try {
      const dir = path.dirname(this.persistPath);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      const tempPath = `${this.persistPath}.tmp.${Date.now()}`;
      fs.writeFileSync(tempPath, JSON.stringify(this.entries, null, 2), 'utf8');
      fs.renameSync(tempPath, this.persistPath);
    } catch {
      // Best-effort persistence
    }
  }

  private load(): void {
    if (!this.persistPath) return;
    try {
      if (fs.existsSync(this.persistPath)) {
        this.entries = JSON.parse(fs.readFileSync(this.persistPath, 'utf8'));
      }
    } catch {
      this.entries = [];
    }
  }
}
